package isikulkas_tartar;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Asus
 */
public class Login extends javax.swing.JFrame {
    int xx, xy;

    /**
     * Creates new form Login
     */
    public dbConnection db;
    
    public Login() {
        initComponents();
        db = new dbConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        customButton1 = new isikulkas_tartar.CustomButton();
        customField1 = new isikulkas_tartar.CustomField();
        customField2 = new isikulkas_tartar.CustomField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(360, 640));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(53, 187, 202));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/isikulkas_tartar/icon/fridge (2).png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/isikulkas_tartar/icon/cancel (2).png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Megrim", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Log In on Vreez");

        customButton1.setBackground(new java.awt.Color(0, 0, 0));
        customButton1.setText("Submit");
        customButton1.setFillClick(new java.awt.Color(153, 0, 153));
        customButton1.setFillDisabled(new java.awt.Color(0, 0, 0));
        customButton1.setFillOver(new java.awt.Color(0, 102, 102));
        customButton1.setFont(new java.awt.Font("Megrim", 1, 14)); // NOI18N
        customButton1.setLineOver(new java.awt.Color(51, 255, 51));
        customButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton1ActionPerformed(evt);
            }
        });

        customField1.setBackground(new java.awt.Color(0, 0, 0, 1));
        customField1.setForeground(new java.awt.Color(153, 153, 153));
        customField1.setText("     Enter username");
        customField1.setFillColor(new java.awt.Color(255, 255, 255));
        customField1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        customField1.setLineColor(new java.awt.Color(0, 0, 0));
        customField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                customField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                customField1FocusLost(evt);
            }
        });
        customField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customField1ActionPerformed(evt);
            }
        });

        customField2.setBackground(new java.awt.Color(0, 0, 0, 1));
        customField2.setForeground(new java.awt.Color(153, 153, 153));
        customField2.setText("     Enter password");
        customField2.setFillColor(new java.awt.Color(255, 255, 255));
        customField2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        customField2.setLineColor(new java.awt.Color(0, 0, 0));
        customField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                customField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                customField2FocusLost(evt);
            }
        });
        customField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customField2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Belum punya akun?");

        jLabel5.setText("Daftar di sini.");
        jLabel5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel5FocusGained(evt);
            }
        });
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(jLabel3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(customField1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(customField2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(customButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 32, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(93, 93, 93))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(customField1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(customField2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(customButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void customButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton1ActionPerformed
        // TODO add your handling code here:
        String username = customField1.getText().trim();
        String password = customField2.getText().trim();

        if (username.isEmpty() || password.isEmpty()) {
            // Show an error message if either the username or password is empty
            JOptionPane.showMessageDialog(this, "Username or password cannot be empty.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                String query = "SELECT * FROM users WHERE username='" + username + "' AND password='" + password + "'";
                ResultSet result = db.selectQuery(query);

                if (result.next()) {
                    // Login successful, proceed to the next step or open another window
                    // setalh button submit
                    JOptionPane.showMessageDialog(this, "Login successful!", "Success", JOptionPane.INFORMATION_MESSAGE);
                    int user_id = result.getInt("id");
                    this.dispose(); // Tutup jendela Login
                    MainPage mainPage = new MainPage(user_id); // Buat instance dari MainPage
                    mainPage.setVisible(true); // Tampilkan jendela MainPage
                } else {
                    // Invalid login, show an error message
                    JOptionPane.showMessageDialog(this, "Invalid username or password.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_customButton1ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void customField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customField1ActionPerformed

    private void customField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customField2ActionPerformed

    private void customField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customField1FocusGained
        // TODO add your handling code here:
        if(customField1.getText().equals("     Enter username")){
            customField1.setText("");
            customField1.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_customField1FocusGained

    private void customField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customField1FocusLost
        // TODO add your handling code here:
        if(customField1.getText().equals("")){
            customField1.setText("     Enter username");
            customField1.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_customField1FocusLost

    private void customField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customField2FocusGained
        // TODO add your handling code here:
        if(customField2.getText().equals("     Enter password")){
            customField2.setText("");
            customField2.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_customField2FocusGained

    private void customField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customField2FocusLost
        // TODO add your handling code here:
        if(customField2.getText().equals("")){
            customField2.setText("     Enter password");
            customField2.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_customField2FocusLost

    private void jLabel5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel5FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5FocusGained

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        //refer ke form register
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private isikulkas_tartar.CustomButton customButton1;
    private isikulkas_tartar.CustomField customField1;
    private isikulkas_tartar.CustomField customField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}


